### ISSUE TITLE
[feature request] tag as addition or instead of folders/groups

### ISSUE THREAD

**Issue by violoncelloCH** [buttercup/buttercup-core#224]
Hi, thanks for buttercup
I would like to have tags and an easy option to filter entrys by these tags in buttercup
would this be possible to implement?

I think tags are in some cases ways easier to use than folders, because i can filter for multiple tags and only entrys with all of these tags appear.
For example I have multiple entries with the tag "server" and some of them with "email" and others with "cms". Then I could easily filter for all entrys containg one or multiple of these tags.

**Comment by perry-mitchell** [comment]
Hmm.. I quite like the idea. Not sure how it'd work in our current interfaces. Definitely happy to explore the idea however.

I wonder how searching might work - right now we have a very simple search dialog in the desktop app which searches by name and details, but I guess we could have something similar for tags too. Showing a selected tag's entries might be more complicated in the UI though.

If we decide to go with this it could be easily implemented in the core, but might take some work on the UI side.

**Comment by violoncelloch** [comment]
We could have like a tabbed interface for switching between folders and tags views:
![2018_08_04 11_44 office lens](https://user-images.githubusercontent.com/22591354/43674992-b4a93ba8-97dc-11e8-8475-d30a3d4cccf8.jpg)
(just a small draft on a recycled paper; if we have clearer ideas I can make a proper new one)
The should present a text box for manual entry of tags (with autocompletion?) and list available tags below. The listed tags should be clickable, so they are moved into the "filter by tags.." textbox and only still relevant tags should stay in the list.
So if I click on the tag "server" only the tags "cms" and "email" should stay in the list below and not the tag "homebanking" for which ther is no entry with a "homebanking" and  a "server" tag.

Apart that I would place a persistant search box over the entries list (also for folders view), so the user has the choice to search or filter by tags. 
ctrl+F is nice, but I think the actual search function is quite hidden, because I had to look for it before I found there is actually a search function. So ctrl+F could just shift focus (and curser) to the always visible search textbox

**Comment by ldexterldesign** [comment]
> Apart that I would place a persistent search box over the entries list (also for folders view), so the user has the choice to search or filter by tags
> 
> ctrl+f is nice, but I think the actual search function is quite hidden, because I had to look for it before I found there is actually a search function. So ctrl+F could just shift focus (and curser) to the always visible search textbox

**Comment by ldexterldesign** [comment]
Hi @violoncelloCH,

Have you considered simply using some name convention for tags?

<img width="1440" alt="screenshot 2019-02-28 at 01 42 07" src="https://user-images.githubusercontent.com/1715809/53533199-2516d880-3afa-11e9-9855-b29cf3d81502.png">

I love tags but can't see a use case for what you're proposing myself

Regards

**Comment by ldexterldesign** [comment]
https://github.com/buttercup/buttercup-desktop/issues/760 - related(?)

**Comment by perry-mitchell** [comment]
I think what @ldexterldesign suggests is a simpler, more natural approach. Tags don't fit as well as just using custom fields. What say you @sallar?

**Comment by perry-mitchell** [comment]
I've added support for tags. They can be added on the `Entry` class, and used to find entries on the `Vault` class. They can also be searched for:

```
#sometag
#sometag #another some-search-term
```

Note that their format is strict: `^[a-z0-9_]+$`;

**Comment by ldexterldesign** [comment]
👋 @perry-mitchell,

Hope you're OK!

Thanks for follow up 👏

Would like to test

What version of desktop app should I find this functionality in?

Homebrew on macOS currently yields me:
<img width="553" alt="Screenshot 2024-01-29 at 18 34 24" src="https://github.com/buttercup/buttercup-core/assets/1715809/4ff0ec5d-0f4c-4667-84aa-a9291d0982bd">
... which seems quite old..? 🤔

Short of updating Homebrew repo is there an update feature I'm missing?

Cheers

**Comment by perry-mitchell** [comment]
It's not available on desktop yet. UI might need a redesign before it's available. Let's see..

With regards to home brew, that's a whole other issue - v6 core is very old. I wonder how home brew is updated? Does a single user submit libraries there?

**Comment by ldexterldesign** [comment]
👋 @perry-mitchell,

Thanks for reply

Will sort my (Homebrew) software issues and look out for this tag addition in future updates 👍

Aside, I have been meaning to find time to contribute to [adding]/[updating] Homebrew (inc. updating the Buttercup formula) - bit off the issue but may I ask how you install software, and on what platform(/s)?

If there's an issue relating to a/the UI update then happy to subscribe to that and offer feedback..?

Cheers!

[adding]: https://docs.brew.sh/Adding-Software-to-Homebrew
[updating]: https://docs.brew.sh/Updating-Software-in-Homebrew

**Comment by perry-mitchell** [comment]
Mac is all DMG these days, as it's the easiest and allows for auto updating. Linux is only AppImage (same reasoning), and Windows portable/NSIS installer.

Unfortunately no issue for the UI yet, as it's a redesign and requires some thought from my side about how much effort is wise to put into it. I'll create an issue when I decide to dive deeper into that topic.
