### ISSUE TITLE
Break on new FileDatasource(path)

### ISSUE THREAD

**Issue by Funisaac** [buttercup/buttercup-core#244]
![screen shot 2019-01-08 at 8 55 17 pm](https://user-images.githubusercontent.com/14154207/50868839-c2ba1b00-1387-11e9-8f0d-126e4e698021.png)

Path can be set to any string and problem persists.

**Comment by perry-mitchell** [comment]
Please share some information regarding your environment. This exact version is working in production, so currently I would suspect that it's your usage that may be erroneous. Let us know what OS, node version, and the code you're using, thanks.

**Comment by perry-mitchell** [comment]
Are you using webpack or anything of the sort? Obviously `FileDatasource` can only be used within Node.

**Comment by Funisaac** [comment]
macOS High Sierra v10.13.6
Node v11.1.0

I am using Node, Webpack and Electron.
Would `FileDatasource` work if I used a string prefixed with `file://`?

**Comment by perry-mitchell** [comment]
Thanks.

> Would FileDatasource work if I used a string prefixed with file://?

Nope, it uses node's `fs` under the hood which does not work within webpack. If you going to use FileDatasource you should keep all of your Buttercup code on the node side. If you want to send data to the electron/web side, consider either:

 * Use [entry facades](https://github.com/buttercup/buttercup-core/blob/master/ENTRY_FACADES.md) to transfer entries to the UI, and send them back for consumption (changes)
 * Use full [archive facades](https://github.com/buttercup/facades) (experimental) to transfer full archive objects to and fro

The reason we'd do this is that Buttercup uses real instances of Archives/Entries etc. that can't be serialised. The facade system supports serialisation but is a little unwieldy in comparison. 

Another option would be to subclass `FileDatasource` so that it uses IPC to communicate to a service on the node side which _reads_ and _writes_ the target file. We've also done this, and it's quite a simple thing to do. In general if you're build a UI application I'd always recommend doing everything on the node side only due to requests not having to obey CORS restraints, which can be a huge pain if you use any other datasource besides the file datasource.

Out of curiosity, what are you building? 😊

**Comment by perry-mitchell** [comment]
I'm going to close this issue as I think the solution is quite apparent. We can reopen if necessary.
